apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: aboutmanjunathgr
spec:
  selector:
    matchLabels:
      app: aboutmanjunathgr
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: aboutmanjunathgr
    spec:
      containers:
        - name: aboutmanjunathgr
          image: manjunathgr/aboutmanjunathgr:_BUILD_NUMBER_
          imagePullPolicy: Always
          ports:
            - containerPort: 80
                     
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: aboutmanjunathgr
spec:
  selector:
    app: aboutmanjunathgr
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: LoadBalancer # type of the service.
